# Generated by Django 2.1 on 2018-11-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='hobby',
            field=models.CharField(default='Book', max_length=32),
        ),
    ]
