# Generated by Django 2.1 on 2018-11-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_students_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='hobby',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
